Vagrant.configure('2') do |config|
  config.vm.box = 'bento/centos-7.2'

  config.cache.scope = :box

  config.vm.provision 'ansible_local' do |a|
    a.sudo = true
    a.playbook = 'ansible/vagrant.yml'
    a.galaxy_role_file = 'ansible/requirements.yml'
    a.galaxy_roles_path = 'ansible/roles'
    a.verbose = 'vv'
  end
end
